# -*- generated by 1.0.9 -*-
import da
_config_object = {}
import sys
from configparser import ConfigParser

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        parser = ConfigParser()
        config_file = 'config/basic_configuration.properties'
        if (len(sys.argv) == 2):
            config_file = sys.argv[1]
            print(('Config file : ' + config_file))
        parser.read(config_file)
        print(parser.get('olympus', 'timeout_in_sec'))
